<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Apple iPhone 13',
                'sku' => 1001,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 99900.99,
                'purchase_price' => 80000.00,
                'discount' => 5,
                'tax' => 10,
                'image' => 'products/product1.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Samsung Galaxy S22',
                'sku' => 1002,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 89900.99,
                'purchase_price' => 75000.00,
                'discount' => 8,
                'tax' => 10,
                'image' => 'products/product2.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Google Pixel 7',
                'sku' => 1003,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 79900.00,
                'purchase_price' => 70000.00,
                'discount' => 6,
                'tax' => 8,
                'image' => 'products/product3.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'OnePlus 11',
                'sku' => 1004,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 72900.00,
                'purchase_price' => 69000.00,
                'discount' => 3,
                'tax' => 5,
                'image' => 'products/product4.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Sony Xperia 5',
                'sku' => 1005,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 84900.00,
                'purchase_price' => 79000.00,
                'discount' => 7,
                'tax' => 9,
                'image' => 'products/product5.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Xiaomi Mi 11',
                'sku' => 1006,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 69900.00,
                'purchase_price' => 64000.00,
                'discount' => 4,
                'tax' => 6,
                'image' => 'products/product6.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Oppo Reno 8',
                'sku' => 1007,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 59900.00,
                'purchase_price' => 55000.00,
                'discount' => 6,
                'tax' => 5,
                'image' => 'products/product7.png',
                'status' => 'Active',
            ],
            [
                'name' => 'Realme GT Neo',
                'sku' => 1008,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 49900.00,
                'purchase_price' => 45000.00,
                'discount' => 5,
                'tax' => 4,
                'image' => 'products/product8.jpeg',
                'status' => 'Active',
            ],
            [
                'name' => 'Samsung 55" 4K Smart TV',
                'sku' => 1009,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 69900.99,
                'purchase_price' => 65000.00,
                'discount' => 10,
                'tax' => 12,
                'image' => 'products/product9.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Bose QuietComfort 35',
                'sku' => 1010,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 29900.99,
                'purchase_price' => 25000.00,
                'discount' => 5,
                'tax' => 8,
                'image' => 'products/product10.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Vacuum Cleaner',
                'sku' => 1011,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 5990.00,
                'purchase_price' => 4400.00,
                'discount' => 7,
                'tax' => 10,
                'image' => 'products/product11.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Electric Toothbrush',
                'sku' => 1012,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 8900.99,
                'purchase_price' => 6500.00,
                'discount' => 15,
                'tax' => 5,
                'image' => 'products/product12.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Canon Camera',
                'sku' => 1013,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 37990.00,
                'purchase_price' => 32000.00,
                'discount' => 5,
                'tax' => 8,
                'image' => 'products/product13.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Sony Headphone',
                'sku' => 1014,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 13490.00,
                'purchase_price' => 9300.00,
                'discount' => 6,
                'tax' => 9,
                'image' => 'products/product14.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Fitness Tracker',
                'sku' => 1015,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 12900.99,
                'purchase_price' => 8110.00,
                'discount' => 8,
                'tax' => 5,
                'image' => 'products/product15.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'KitchenAid Mixer',
                'sku' => 1016,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 3990.00,
                'purchase_price' => 2350.00,
                'discount' => 10,
                'tax' => 8,
                'image' => 'products/product16.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Nikon D7500 DSLR Camera',
                'sku' => 1017,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 84900.99,
                'purchase_price' => 65750.00,
                'discount' => 5,
                'tax' => 7,
                'image' => 'products/product17.jpg',
                'status' => 'Active',
            ]
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
