<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Apple iPhone 13',
                'sku' => 1001,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 999.99,
                'purchase_price' => 800.00,
                'discount' => 5,
                'tax' => 10,
                'image' => 'products/product1.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Samsung Galaxy S22',
                'sku' => 1002,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 899.99,
                'purchase_price' => 750.00,
                'discount' => 8,
                'tax' => 10,
                'image' => 'products/product2.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Google Pixel 7',
                'sku' => 1003,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 799.00,
                'purchase_price' => 700.00,
                'discount' => 6,
                'tax' => 8,
                'image' => 'products/product3.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'OnePlus 11',
                'sku' => 1004,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 729.00,
                'purchase_price' => 690.00,
                'discount' => 3,
                'tax' => 5,
                'image' => 'products/product4.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Sony Xperia 5',
                'sku' => 1005,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 849.00,
                'purchase_price' => 790.00,
                'discount' => 7,
                'tax' => 9,
                'image' => 'products/product5.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Xiaomi Mi 11',
                'sku' => 1006,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 699.00,
                'purchase_price' => 640.00,
                'discount' => 4,
                'tax' => 6,
                'image' => 'products/product6.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Oppo Reno 8',
                'sku' => 1007,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 599.00,
                'purchase_price' => 550.00,
                'discount' => 6,
                'tax' => 5,
                'image' => 'products/product7.png',
                'status' => 'Active',
            ],
            [
                'name' => 'Realme GT Neo',
                'sku' => 1008,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 499.00,
                'purchase_price' => 450.00,
                'discount' => 5,
                'tax' => 4,
                'image' => 'products/product8.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Samsung 55" 4K Smart TV',
                'sku' => 1009,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 699.99,
                'purchase_price' => 650.00,
                'discount' => 10,
                'tax' => 12,
                'image' => 'products/product9.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Bose QuietComfort 35',
                'sku' => 1010,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 299.99,
                'purchase_price' => 250.00,
                'discount' => 5,
                'tax' => 8,
                'image' => 'products/product10.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Vacuum Cleaner',
                'sku' => 1011,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 599.00,
                'purchase_price' => 540.00,
                'discount' => 7,
                'tax' => 10,
                'image' => 'products/product11.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Electric Toothbrush',
                'sku' => 1012,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 89.99,
                'purchase_price' => 75.00,
                'discount' => 15,
                'tax' => 5,
                'image' => 'products/product12.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Canon Camera',
                'sku' => 1013,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 3799.00,
                'purchase_price' => 3200.00,
                'discount' => 5,
                'tax' => 8,
                'image' => 'products/product13.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Sony Headphone',
                'sku' => 1014,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 349.00,
                'purchase_price' => 300.00,
                'discount' => 6,
                'tax' => 9,
                'image' => 'products/product14.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Fitness Tracker',
                'sku' => 1015,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 129.99,
                'purchase_price' => 110.00,
                'discount' => 8,
                'tax' => 5,
                'image' => 'products/product15.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'KitchenAid Mixer',
                'sku' => 1016,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 399.00,
                'purchase_price' => 350.00,
                'discount' => 10,
                'tax' => 8,
                'image' => 'products/product16.jpg',
                'status' => 'Active',
            ],
            [
                'name' => 'Nikon D7500 DSLR Camera',
                'sku' => 1017,
                'unit' => 'piece',
                'unit_value' => '1',
                'selling_price' => 849.99,
                'purchase_price' => 750.00,
                'discount' => 5,
                'tax' => 7,
                'image' => 'products/product17.jpg',
                'status' => 'Active',
            ]
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
